### ISSUE TITLE
关于修改各个仓库的代码的规则

### ISSUE THREAD

**Issue by HansLjy** [ezoiteam/Forum#1]
# 提交代码的规范

1. 所有人都必须先pull request，不要直接提交
1. request 应该一个项目找一个人审核（投票决定）
1. 接下来应该统一代码风格（都投票决定）：
    > * 大括号是否换行
    > * 各种空格规范
    > * 变量命名（一些常用变量应该怎么命名，以及tmp不要泛滥）
    > * struct vs class
    > * 函数的各种接口
    > * 对可读性的一些要求（注释、单行字符数等等）
    > * 等等等等

**Comment by Taserita** [comment]
orz

**Comment by Taserita** [comment]
orz

**Comment by Taserita** [comment]
*** <-orz

**Comment by CHN-ChenYi** [comment]
第三条中的大部分没有任何可行性（除了函数接口和可读性有讨论价值）
